# example profiles.yml file
testing123:
  target: 'dev'
  outputs:
    dev:
      type: 'postgres'
      host: 'localhost'
      user: 'postgres'
      password: 'password'
      dbname: 'testing123'
      schema: 'public'
      port: 5432
      threads: 4